# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8f9488f092d3e9d9580455ec3401bf697488b5d5a1fce96029dbb5d8f6fabc22015f7f46d0933a840931ada7f4c1703479a90f6bb676650cda97b5fde3c8a4aa

test:
  secret_key_base: b2cbc651def9127b7d85d474786e5a8438f353ff7142a393924415b7d1aa66d9246454de1a2b6a4f1205c063da5fb456eb853b47274007f9a5b8592990fe769d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
